### ISSUE TITLE
Import features from RigidBodyTreeInspector.jl

### ISSUE THREAD

**Issue by rdeits** [JuliaRobotics/MeshCatMechanisms.jl#2]
- [x] creating geometry from mechanisms
- [x] animation
- [ ] Interact.jl manipulation
- [x] ODE callback
- [x] visualizing CartesianFrame3D and Point3D

**Comment by rdeits** [comment]
It also might be time to move to https://github.com/JuliaGizmos/InteractNext.jl

**Comment by rdeits** [comment]
Or, in fact, to render the sliders in the MeshCat viewer instead of relying on the notebook to display them. That would make manipulation work outside of the Jupyter notebook and would generally be pretty slick.

**Comment by rdeits** [comment]
I'll add manipulation once https://github.com/JuliaLang/METADATA.jl/pull/14828 comes in

**Comment by piever** [comment]
Just a quick heads up: InteractBase v0.1.0 is merged but I recommend waiting a little bit before using it as I'm still in the process of finalizing the API (though basic things like `slider(range)` or `@manipulate` are very unlikely to change). Current API is available [here](https://piever.github.io/InteractBase.jl/latest/api_reference.html), I'll open an issue to discuss the new API so if you want you can give your input.
